version: "3.8"

networks:
  ops-network: { }

services:
  # LocalStack
  localstack:
    container_name: "ops-inbound-localstack"
    image: localstack/localstack:latest
    networks:
      - ops-network
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/:/mount
      - ./localstack/init-scripts:/etc/localstack/init/ready.d

  database:
    container_name: ops-inbound-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ops-inbound-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: [ 'CMD-SHELL', "pg_isready -U postgres -d ops-inbound-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always